INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (32, '2', '2', '$2b$10$Lfr0oHRSxpTHlwaXGOoCKuzs6NqJExs7JAeEgyz8WfdCOEbZ5hz0G', '2', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (34, 'Мася', 'Белецкий', '$2b$10$eJbHoONLR8zHNbgV1Il7hu9d99J4ctuchpO7V6OK3gJHUT4V2zdaW', 'masya', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (35, 'Женя', 'Петров', '$2b$10$6qzMqFn748fWyRItIQcHg.CHQy1iDLef56gXEuLy2pJJ43yP8Sim2', 'zenya', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (36, 'Valerii', 'Leontiev', '$2b$10$KPu0OG7bGB/tmyh4GF4y2eHdvfuMyJVx/QvBmXB4CU7sHb828GXSO', 'Valera', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (38, 'Иван', 'Иванов', '$2b$10$TmvxNK7qYQHgoGBE9DiqlOu8BHF.Ejyhr4cNGVKxbdz5c.mDTUEeG', 'Vanyok', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (39, 'Alex', 'Alexov', '$2b$10$YBOEfZm/plyLnWd0zmsrIePk6RU0uyhwn.BFrxmny.4IgPrlNiZM6', 'Alesha', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (37, 'Иванt', 'Иванов', '$2b$10$8IxfhJ5dc2EC/7gUBdJ9l.jU1gadZ/I4y83SYuCNaizNf3ugVGvPe', 'Vanya', 'admin');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (40, '2', '2', '$2b$10$YE6V3WXHA3aMUorGdp3tpuB4skIVR9lX.SmuA5eT75WPU6WmZBCOG', '2', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (41, 'ew', 'we', '$2b$10$NogwmI1axIreP9Pltc9wz.28JYQoNKZOmf/iDoCJUZR9.8R5Irbka', '45', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (44, 'Игорь', 'Мельниченко', '$2b$10$JX1FA7Z7vpUQVlKywczFOuk2b7RSqEwEk849SDc2VF3JWDHWh.nWy', 'igorok', 'admin');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (45, 'Александр', 'Вальков', '$2b$10$EKMmXNFYb76V306KcVQHye1n0avbAqNRRKSWczwrRxLjduDFx/sZy', 'alexvalkov', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (46, 'ilya', 'bebekov', '$2b$10$UaVGgp841y3QolQ.d7aml.o6umkFrpe3zrhwv0she90uLWk/WXUWW', 'iliabe', 'admin');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (47, 'kekeker', 'kekeke', '$2b$10$Fo5k/1QRc8iBy7xlXsP.RuCSjjhPgEPWuOzU.CamfWMtyjv/YyQmu', 'kekeke', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (48, 'Maxim', 'Belecky', '$2b$10$CNvf.cRsJy/y5ceLPqKJuudpSu2QS9f.RR8MTj0sC3QOe7p7kIVDO', 'max', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (49, 'Максим', 'Белецкий', '$2b$10$E4rQq5BPt/nAtKAfwylmpesxEQRftXcfz7PJFChR4l/9HX2IAEjdC', 'LLLLL', 'admin');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (50, 'Максим', 'Лавров', '$2b$10$nVyr9dHu/Rh5nitxJ4RkhuhV35A9E1/eFRlY32n1.cu87I/IXVq6a', 'Maxim', 'user');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (51, 'Igor', 'Мельниченко', '$2b$10$pci1yQaxYumH2mSI.89Tpu9.aFSh/GU4f.cPkdIQBtCaEJhVCJRCK', 'Igor', 'admin');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (42, 'МаксимEE', 'Белецкий', '$2b$10$xJPUOhIogpLipqGJG2OqNuFvbLi42KwX23UAhcmObLyPPbZduB3La', 'maxim', 'admin');
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (9, 'Максим', 'Белецкий', '321', 'maxim', NULL);
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (4, 'Aliceerr', 'Smith', '333', 'alice.smith', NULL);
INSERT INTO "person" ("id", "name", "surname", "password", "login", "role") VALUES (15, 'admin', '2', '$2b$10$HTk25AOAASpD.T.pSQV8z.EhroxDBFDKJLQ4XgkCqAhUThSYB1F5W', '2', NULL);
INSERT INTO "brands" ("brand_id", "name") VALUES (1, 'YAMAHA');
INSERT INTO "brands" ("brand_id", "name") VALUES (6, 'Rockdale');
INSERT INTO "brands" ("brand_id", "name") VALUES (2, 'Fenderук');
INSERT INTO "brands" ("brand_id", "name") VALUES (8, 'Defender');
INSERT INTO "brands" ("brand_id", "name") VALUES (10, 'HOHNER');
INSERT INTO "instrument_types" ("type_id", "name") VALUES (1, 'Гитара');
INSERT INTO "instrument_types" ("type_id", "name") VALUES (2, 'Барабан');
INSERT INTO "instrument_types" ("type_id", "name") VALUES (6, 'Маракасы');
INSERT INTO "instruments" ("instrument_id", "name", "brand_id", "type_id", "description", "image_url") VALUES (20, 'Fender', 1, 1, '4', 'https://avatars.mds.yandex.net/get-mpic/4776349/img_id1233526882659691554.jpeg/orig');
INSERT INTO "instruments" ("instrument_id", "name", "brand_id", "type_id", "description", "image_url") VALUES (22, 'HOHNER', 10, 1, 'ГИТАРА ТОП', 'https://cache3.youla.io/files/images/720_720_out/5a/29/5a292b80b261ff831746dae4.jpg');
INSERT INTO "instruments" ("instrument_id", "name", "brand_id", "type_id", "description", "image_url") VALUES (1, 'YAMAHA F370Cc', 2, 1, 'Yamaha F370 - это акустическая вестерн-гитара из ели и нато, 21 ладом и хромированными колками.Прекрасный звук и отличное качество изготовления по демократичной цене - отличительные особенности гитары серии F.', 'https://musicstyle-shop.ru/thumb/2/9EuXOVsyD3_qBAkh3BPbXQ/r/d/370-2.jpg');
INSERT INTO "instruments" ("instrument_id", "name", "brand_id", "type_id", "description", "image_url") VALUES (10, 'Fender', 2, 1, 'fdfdfdf', 'https://avatars.mds.yandex.net/get-mpic/4776349/img_id1233526882659691554.jpeg/orig');
INSERT INTO "instruments" ("instrument_id", "name", "brand_id", "type_id", "description", "image_url") VALUES (12, 'YAMAHA F370Cc', 2, 1, 'Yamaha F370 - это акустическая вестерн-гитара из ели и нато, 21 ладом и хромированными колками.Прекрасный звук и отличное качество изготовления по демократичной цене - отличительные особенности гитары серии F.', 'https://musicstyle-shop.ru/thumb/2/9EuXOVsyD3_qBAkh3BPbXQ/r/d/370-2.jpg');
INSERT INTO "inventory" ("inventory_id", "instrument_id", "quantity", "price", "condition") VALUES (1, 1, 10, '99.99', 'Condition');
INSERT INTO "addresses" ("address_id", "customer_id", "street", "city", "state", "zip_code") VALUES (4, NULL, 'Sovetskaya', 'Trud', 'TRUD', '10010');
INSERT INTO "addresses" ("address_id", "customer_id", "street", "city", "state", "zip_code") VALUES (3, NULL, '12345 Main St', 'River City', 'NY', '10001');
INSERT INTO "addresses" ("address_id", "customer_id", "street", "city", "state", "zip_code") VALUES (6, NULL, 'Арбат', 'Москва', 'Россия', '232112');
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (2, 4, '2024-10-26T08:00:00.000Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (6, 4, '2024-12-09T21:00:00.000Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (11, 32, '2024-12-12T21:00:00.000Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (14, 32, '2024-12-12T22:28:04.246Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (15, 32, '2024-12-12T22:30:34.664Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (12, 32, '2024-12-01T21:00:00.000Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (16, 32, '2024-12-12T22:32:04.499Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (17, 32, '2024-12-15T16:32:01.904Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (18, 32, '2024-12-15T19:13:28.471Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (19, 32, '2024-12-19T21:00:00.000Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (20, 32, '2024-12-18T21:00:00.000Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (21, 32, '2024-12-15T19:21:52.462Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (22, 32, '2024-12-15T19:44:45.545Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (23, 32, '2024-12-05T21:00:00.000Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (24, 32, '2024-12-12T21:00:00.000Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (25, 32, '2024-12-05T21:00:00.000Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (26, 32, '2024-12-16T01:30:14.661Z', 3);
INSERT INTO "orders" ("order_id", "customer_id", "order_date", "shipping_address_id") VALUES (27, 32, '2024-12-19T21:00:00.000Z', 3);
INSERT INTO "order_items" ("order_item_id", "order_id", "inventory_id", "quantity", "price_at_purchase") VALUES (2, 2, 1, 4, '199.99');
INSERT INTO "order_items" ("order_item_id", "order_id", "inventory_id", "quantity", "price_at_purchase") VALUES (5, 2, 1, 5, '200');
INSERT INTO "order_items" ("order_item_id", "order_id", "inventory_id", "quantity", "price_at_purchase") VALUES (6, 2, 1, 10, '21213');
INSERT INTO "order_items" ("order_item_id", "order_id", "inventory_id", "quantity", "price_at_purchase") VALUES (9, 2, 1, 1, '1');
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('HJCYtmPOgjreExpF8TI1roemwEv1mw3i', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('hXRihFa8FrEujiy70MVXvd70HpBFAhJa', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('VdjWwQlg8ErrQ5k-nHENw5ZC00gaRAi-', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('kCKc04PYdF9_4rW5TtO0dyo4uSNIEN-t', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('MvkGb0g0wamxtvipmjoLE7pQmzuT_htk', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('sAdpMG9pElF8x0YHxTPx-NRvPhiytDQh', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('8daKLe9Y13MU0SBID862BY2mZMFI5P_j', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('iFs7Fu38fq7dFTeDaOAAC_tjjgGwyB7K', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('iiDv0XmcqeMwCHELNRh9N5SpLyZSPOvm', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('s61Sde7R2q9rcXmFkq1TKqNSfhTfks0A', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('u8le1CuA3cMIMIjB8sEGWsbzgNogFjPv', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('4S0Mb3V8k39cd6LJaHMJLNOg42ijPnwO', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('0z1nKZH0JXTyqBSMXxuzeEe69PcAte75', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('h7c4llFLlJNaDikTgakhB_IvKkTmFn2R', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('1fLxyWzOZaLlqCOHD9VzkM1Mr_LHAp4A', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('B_5pbOpBc77ROEC_dBM5VoT1QPSDFjbX', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('E500DT1LoVwdeDiIBZ7mRCgmE5LULcXM', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('ToQ-koQspvTeHd6NYwQRD5FzBhmlbx3d', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('l3vN6wWd-AhDkioXa-mR4TjS0mXmERhR', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('ytvjglonzUxVk2TNBrq4qHHivXtvP6qN', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('Y-7w49bCSyICLHCGnj-TxCPTX_KeR62z', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('Y_WwnOPPDUUSdCWiw2wlJ0y2HOMA0PIv', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('kEKcVC-KoHrlF3pTd1K0yipSSI2HP1DP', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('NtdcVyPeZxeiZ6PiYXwrkAmwZlAIhMiZ', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('da33SKjY4QTz_cJwM6nrVwUZsiEHYAVu', [object Object]);
INSERT INTO "user_carts" ("session_id", "cart") VALUES ('FVl8P4N9kJwlPYFLXhtXiD608YC-QVMg', [object Object]);
