name: codestylecheck

on:
  push:
    branches:
      - new

  pull_request:
    branches:
      - new

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest
    steps:
      - name: git clone repo
        uses: actions/checkout@v2

      - name: Set version node
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint